name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USR }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            whoami
            mkdir testq
            cd testq
            git clone git@github.com:u21513768/testrepo.git
            echo 'Deployment successful
