name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USR }}
        password: ${{ secrets.SSH_KEY }}
        script: mkdir testq && cd testq && git clone git@github.com:u21513768/testrepo.git && echo 'success'
