name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USR }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            mkdir testq
            cd testq
            git clone https://github.com/COS301-SE-2024/IoT-DIRfram.git
            echo 'Deployment successful'
